{
    "name": "YousenTech Booking",
    'version': '17.0.1.0',
    'summary': "Modern event and stay booking operations",
    'description': 'Booking System.',
    'category': 'Tools',
    'author': 'Generated by Yousentech Team',
    "depends": ["base", "web", "mail", "account", "product"],
     "data": [

        "security/booking_security.xml",
        "security/ir.model.access.csv",
        "data/booking_sequence.xml",
        "data/booking_cron.xml",
        "views/booking_views.xml",
        "views/booking_menu.xml"
    ],
    "assets": {"web.assets_backend": ["yousentech_booking/static/src/booking_os/**/*"]},
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}